### ISSUE TITLE
Problem processing .ico/.png files

### ISSUE THREAD

**Issue by eddieevt-DXC** [mkrd/Flask-Squeeze#15]
I'm getting the following exception when running my app:
```bash
Traceback (most recent call last):
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\werkzeug\middleware\proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask\app.py", line 1847, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask\app.py", line 2340, in process_response
    response = self.ensure_sync(func)(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask_squeeze\log.py", line 50, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask_squeeze\debug.py", line 44, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask_squeeze\flask_squeeze.py", line 258, in after_request
    self.run(response)
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask_squeeze\flask_squeeze.py", line 207, in run
    self.execute_compress(response, ResourceType.static)
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask_squeeze\log.py", line 50, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\FlaskApp\venv\Lib\site-packages\flask_squeeze\flask_squeeze.py", line 155, in execute_compress
    f"used {self.encode_choice.value}"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

It's accompanied by an HTML 500 on the .ico file.
```bash
 127.0.0.1 - - [04/Jan/2024 12:20:33] "GET /static/dist/img/favicon.ico HTTP/1.1" 500 -
```

Navigating on the page then clicking the Back button in the browser (latest Firefox) loads the favicon but gives HTML 500 and a couple of the same exceptions on the PNG files instead. 
```bash
 127.0.0.1 - - [04/Jan/2024 12:51:56] "GET /static/dist/img/logo.png HTTP/1.1" 500 -
 127.0.0.1 - - [04/Jan/2024 12:51:56] "GET /static/dist/img/bot.png HTTP/1.1" 500 -
```

When this happens, the respective images would not get rendered on the page, due to the HTML 500 and Flask would restart due to an exception being thrown. Everything else loads fine.

I added the following conditional on line 152 of `C:\Users\User\FlaskApp\venv\Lib\site-packages\flask_squeeze\flask_squeeze.py`:
```python
 if self.encode_choice is not None:
```

This solved the issue of restarting, I am evaluating whether it also corrects the HTML 500 behaviour.

**Comment by mkrd** [comment]
Hi @eddieevt-DXC ! Which version are you using? This might be an issue of an older release that is fixed in the current release

**Comment by eddieevt-DXC** [comment]
Hi @mkrd, 3.0.8 - latest in pypi. Is there a later one?

**Comment by mkrd** [comment]
Hey @eddieevt-DXC! Thats indeed super weird that the first log passed. To avoid the issue entirely, I changed the code so that the minify/encode choices are always passed explicitly and not as class attributes.

It would be great if you could update to 3.0.9 and check if the issue persists!

**Comment by eddieevt-DXC** [comment]
I have monitored it for a while and it hasn't happened again. I think the issue is clear to close. 
Thank you for the prompt response! :)
